require: 
  - rubocop-performance
  - rubocop-rails
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - lib/generators/**/templates/*.rb
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'

Style/AsciiComments:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb
    - lib/generators/**/*.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/MultilineBlockChain:
  Enabled: false

#################### Metrics ###############################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Max: 30
  IgnoredMethods: []
  Exclude:
    - Guardfile
    - spec/**/*_spec.rb

Metrics/BlockNesting:
  CountBlocks: false
  Max: 3

Metrics/ClassLength:
  CountComments: false
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

#################### Lint ##################################

Lint/UnusedBlockArgument:
  IgnoreEmptyBlocks: true
  AllowUnusedKeywordArguments: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

#################### Performance ###########################

Performance/DoubleStartEndWith:
  IncludeActiveSupportAliases: false

Performance/RedundantMerge:
  MaxKeyValuePairs: 2

#################### Rails #################################

Rails/ActionFilter:
  EnforcedStyle: action

#################### Naming ###########################

Naming/VariableNumber:
  Enabled: false