version: '3'
services:
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - "app_tmp:/app/tmp"
    ports:
      - "3003:3000"
    env_file:
      - '.env'
    stdin_open: true
    tty: true
volumes:
  app_tmp:
   driver: local